#web服务配置
server:
  #端口
  port: 9090

#Spring 配置
spring:
  #数据库配置
  datasource:
   url: jdbc:mysql://localhost:3306/db_dormitory?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
   username: root
   password: 123456

#   url: jdbc:mysql://8.134.24.52:3306/db_dormitory?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
#   username: szy095
#   password: 123
   driver-class-name: com.mysql.cj.jdbc.Driver